#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-1.6 ]
then
	cd $OPENSHIFT_DATA_DIR
	mkdir gradle
	wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
	unzip gradle-1.6-bin.zip
	rm -f gradle-1.6-bin.zip
fi
